In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.dtype)

int64


In [9]:
a = a.astype(np.float64)
print(a.dtype)

float64


In [18]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
c = a.reshape(5,2)
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
a = np.zeros((3,4),dtype=np.int32)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [22]:
b = np.zeros_like(c)
b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [28]:
b = np.random.randint(3,10,(2,3))
b

array([[6, 7, 4],
       [3, 4, 8]], dtype=int32)

In [29]:
b = np.random.uniform(50,100,(3,4))
b

array([[70.27750986, 83.48102231, 69.59545137, 79.2220827 ],
       [61.57470861, 68.704637  , 68.61950441, 51.52331486],
       [75.40799992, 90.55559822, 96.27276626, 75.26803098]])

In [32]:
b = np.linspace(1,90,20)
b

array([ 1.        ,  5.68421053, 10.36842105, 15.05263158, 19.73684211,
       24.42105263, 29.10526316, 33.78947368, 38.47368421, 43.15789474,
       47.84210526, 52.52631579, 57.21052632, 61.89473684, 66.57894737,
       71.26315789, 75.94736842, 80.63157895, 85.31578947, 90.        ])

In [33]:
b = np.logspace(1,90,20)
b

array([1.00000000e+01, 4.83293024e+05, 2.33572147e+10, 1.12883789e+15,
       5.45559478e+19, 2.63665090e+24, 1.27427499e+29, 6.15848211e+33,
       2.97635144e+38, 1.43844989e+43, 6.95192796e+47, 3.35981829e+52,
       1.62377674e+57, 7.84759970e+61, 3.79269019e+66, 1.83298071e+71,
       8.85866790e+75, 4.28133240e+80, 2.06913808e+85, 1.00000000e+90])

In [38]:
b = np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
b = np.eye(4,3,1)
b

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
s = {1,2,3,4,5}
a = np.array(list(s))
a

array([1, 2, 3, 4, 5])

In [45]:
t = (1,2,3,4,5)
a = np.array(t)
a

array([1, 2, 3, 4, 5])

In [47]:
dic = {'a':1,'b':2,'c':3}
a = np.array(list(dic.keys()))
a

array(['a', 'b', 'c'], dtype='<U1')

In [48]:
dic = {'a':1,'b':2,'c':3}
a = np.array(list(dic.values()))
a

array([1, 2, 3])

In [50]:
dic = {'a':1,'b':2,'c':3}
a = np.array(dic.items())
a

array(dict_items([('a', 1), ('b', 2), ('c', 3)]), dtype=object)

In [51]:
a1 = np.arange(12,dtype=np.float32).reshape(3,4)
a1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [54]:
print(a1.ndim)

2


In [55]:
print(a1.size)

12


In [56]:
print(a1.itemsize)
print(a1.dtype)

4
float32


In [58]:
a1 = a1.astype(np.int32)
print(a1.dtype)

int32
