In [1]:
import numpy as np


In [2]:

oneD = np.array([1,2,3,4,5,6,7,8,9,10])
print(oneD.ndim,oneD.shape)

1 (10,)


In [ ]:
twoD = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
print(twoD.ndim,twoD.shape)

1 (2, 5)


In [5]:
threeD = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,2,3)
print(threeD.ndim,threeD.shape)

3 (2, 2, 3)


In [6]:
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
filled = np.full((3,3),7)
filled

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

###  Create an array of even numbers between 10 and 50 using arange. 

In [23]:
a = np.arange(10,51)
print(type(a))

<class 'numpy.ndarray'>


In [24]:
b = a[a%2 == 0]
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#  Create a 4×4 matrix from 0–15. Then , extract: 
● the first row 
● the last column 
● a 2×2 subarray from the center

In [33]:
mat = np.arange(0,16).reshape(4,4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
first_row = mat[0:1,::]
first_row

array([[0, 1, 2, 3]])

In [41]:
last_col = mat[::,3:4]
last_col

array([[ 3],
       [ 7],
       [11],
       [15]])

In [42]:
sub_array_from_center = mat[1:3,1:3]
sub_array_from_center

array([[ 5,  6],
       [ 9, 10]])

#. Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [43]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a = [1,2,3]
add = np.add(arr,a)
add

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

#Given two arrays A and B, compute: 
● (A + B) / 2 
● A ** 2 + B**2

In [51]:
A = np.arange(1,10)
B = np.arange(1,10)
# x = np.divide(np.add(A,B),2)
x = np.add(A,B)/2
x

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
res = A**2 + B**2
res

array([  2,   8,  18,  32,  50,  72,  98, 128, 162])